"""Closed vocabularies used by the minimum conservation model."""

from __future__ import annotations

from enum import Enum


class ValueEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class ActorKind(ValueEnum):
    HUMAN = "HUMAN"
    MODEL = "MODEL"
    SYSTEM = "SYSTEM"
    EXTERNAL = "EXTERNAL"


class EpistemicStatus(ValueEnum):
    FACT = "FACT"
    OBSERVATION = "OBSERVATION"
    INFERENCE = "INFERENCE"
    ESTIMATED = "ESTIMATED"
    UNKNOWN = "UNKNOWN"
    CONFLICTED = "CONFLICTED"
    SIMULATED = "SIMULATED"
    ASSUMPTION = "ASSUMPTION"
    RECOMMENDATION = "RECOMMENDATION"
    DECISION = "DECISION"


class AuthorityStatus(ValueEnum):
    NONE = "NONE"
    PROPOSED = "PROPOSED"
    HUMAN_AUTHORIZED = "HUMAN_AUTHORIZED"
    CANONICAL = "CANONICAL"
    EXECUTED = "EXECUTED"


class OriginStatus(ValueEnum):
    HUMAN_ORIGINATED = "HUMAN_ORIGINATED"
    MACHINE_ORIGINATED = "MACHINE_ORIGINATED"
    HUMAN_ADOPTED_MACHINE_OUTPUT = "HUMAN_ADOPTED_MACHINE_OUTPUT"
    EXTERNAL_ORIGINATED = "EXTERNAL_ORIGINATED"


class UncertaintyState(ValueEnum):
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"
    UNCERTAIN = "UNCERTAIN"
    CONFLICTED = "CONFLICTED"


class TemporalScope(ValueEnum):
    HISTORICAL = "HISTORICAL"
    CURRENT = "CURRENT"
    FUTURE = "FUTURE"
    SIMULATION = "SIMULATION"
    UNKNOWN = "UNKNOWN"


class CanonicalState(ValueEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    CANONICAL = "CANONICAL"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"
    DELETED = "DELETED"


class Dimension(ValueEnum):
    CONTENT = "CONTENT"
    PROVENANCE = "PROVENANCE"
    EPISTEMIC_STATUS = "EPISTEMIC_STATUS"
    AUTHORITY = "AUTHORITY"
    HUMAN_ORIGIN = "HUMAN_ORIGIN"
    UNCERTAINTY = "UNCERTAINTY"
    TEMPORAL_STATE = "TEMPORAL_STATE"
    EVIDENCE = "EVIDENCE"
    CANONICALITY = "CANONICALITY"
    FUNCTIONAL_CONTRACT = "FUNCTIONAL_CONTRACT"
    LINEAGE = "LINEAGE"


class TransitionKind(ValueEnum):
    DERIVATION = "DERIVATION"
    HUMAN_ADOPTION = "HUMAN_ADOPTION"
    EPISTEMIC_PROMOTION = "EPISTEMIC_PROMOTION"
    AUTHORITY_ESCALATION = "AUTHORITY_ESCALATION"
    TEMPORAL_RECLASSIFICATION = "TEMPORAL_RECLASSIFICATION"
    CANONICALIZATION = "CANONICALIZATION"
    EVIDENCE_REDACTION = "EVIDENCE_REDACTION"
    FUNCTIONAL_CHANGE = "FUNCTIONAL_CHANGE"


class EvidenceKind(ValueEnum):
    SOURCE_OBSERVATION = "SOURCE_OBSERVATION"
    INDEPENDENT_VERIFICATION = "INDEPENDENT_VERIFICATION"
    HUMAN_AUTHORIZATION = "HUMAN_AUTHORIZATION"
    CITATION = "CITATION"
    MODEL_CONSENSUS = "MODEL_CONSENSUS"
    ACTOR_REPORT = "ACTOR_REPORT"
    EXECUTION_RECORD = "EXECUTION_RECORD"
    FUNCTIONAL_VALIDATION = "FUNCTIONAL_VALIDATION"


class VerificationStatus(ValueEnum):
    PASS = "PASS"
    PASS_WITH_DECLARED_TRANSFORMATION = "PASS_WITH_DECLARED_TRANSFORMATION"
    REJECT = "REJECT"
    UNVERIFIABLE = "UNVERIFIABLE"
